### ISSUE TITLE
一些域名

### ISSUE THREAD

**Issue by Anyiran** [MatcherAny/whitelist.pac#11]
miaopai.com
现在是走代理的，导致微博视频无法打开
tbcache.com
ottcn.com
gitv.tv
www.zzguifan.com
gisroad.com

**Comment by AnyWAT** [comment]
大佬忙，再说 auto switch 模式可自添加上述地址走“直接连接”？

**Comment by Anyiran** [comment]
> 
> 
> 大佬忙，再说 auto switch 模式可自添加上述地址走“直接连接”？

chrome倒是可以这么做，可惜firefox上的switchomega不支持pac模式，不能在auto switch里默认走pac
firefox网络配置里的pac模式也不支持添加例外域名

**Comment by AnyWAT** [comment]
貌似 firefox 支持本地PAC？

**Comment by Anyiran** [comment]
> 
> 
> 貌似 firefox 支持本地PAC？

对的，自己改了改解决了，感谢
