### ISSUE TITLE
为什么不在白名单里的网站，能够找到proxy？

### ISSUE THREAD

**Issue by alexya** [MatcherAny/whitelist.pac#14]
如图所示，我按照你的图示设置了autoswitch 的 默认访问通过whitepac，并且也没有做任何其它指定。使用了一下，可以正常工作。
但是，我不理解，为什么不在whitepac里面的网站，比如 google.com，怎么能够访问，我并没有指定其它的访问方式呢？
谢谢。
![](https://github.com/MatcherAny/whitelist.pac/blob/master/img/chrome-4.png?raw=true)

**Comment by AnyWAT** [comment]
貌似：
白名单，在其内的直连，否则代理；
黑名单，在其内的代理，否则直连。

**Comment by alexya** [comment]
兄弟，感谢关注/回复。
不过，我不清楚 - 是不是我没有描述清楚，或者 - 你没有理解我的意思。
“白名单，在其内的直连，否则代理；” 你说的这句话，我懂，但这个只是“理论”、原理。
在switchyomega里面，却不是这样实现的（至少我现在看到这张图，不是这样实现的）。
如上图，在这里，auto switch 仅仅指定了 “默认情景模式” 下，使用whitepac。
这我就不懂了，我不理解的是 - 根本就没有指定代理，这个auto switch怎么访问google.com的？

**Comment by alexya** [comment]
@AnyWAT 我搞清楚了。
读了一下whitepac的源文件，里面hardcode了local proxy的地址 
一般我们本地起的客户端，都是127.0.0.1:1080，我把本地的客户端关闭了，这个就不工作了。
thx.
```
var wall_proxy = "SOCKS5 127.0.0.1:1080;";
var nowall_proxy = "DIRECT;";
var direct = "DIRECT;";
var ip_proxy = "DIRECT;";
```
p.s. 发现这个白名单也很麻烦呢。我个人很多经常访问的网站，就不在里面（这个貌似太个人化了），比如 chiphell.com, etc.

**Comment by AnyWAT** [comment]
> 我个人很多经常访问的网站，就不在里面（这个貌似太个人化了），比如 chiphell.com, etc.

手动添加切换规则：走代理或直连
