### ISSUE TITLE
为什么我始终有一些资源加载失败呢？

### ISSUE THREAD

**Issue by alexya** [MatcherAny/whitelist.pac#15]
如图
不论我是用黑名单gfwlist 还是白名单whitepac方法，甚至直接“所有流量全走代理”，访问一些网站时，都会提示我 "Resources that failed to load". 尤其是google想关的，还有一些小图片资源。有时候一个网站打开，大片大片“空白占位图片”显示在那儿，非常影响网站浏览。
比如：gstatic.com googlesyndication.com githubusercontent.com
可是，这些地址，我都检查了一下，明明都在gwflist里面/或者不在whitepac里面，为啥还是资源加载失败？

![image](https://user-images.githubusercontent.com/2831220/61850744-99a64580-aee7-11e9-95e4-b4cef7a4e574.png)

**Comment by AnyWAT** [comment]
已在明确规则内的资源加载失败，貌似（代理）网速的锅，或需刷新。。。

**Comment by alexya** [comment]
@AnyWAT 
是这样的啊？可是我刷新几次，还是会有提示，而且，提示的那几个网站（比如：*.reddit.com, *.gstatic.com）也都是一样的。
这种情况不论是在家（用自己的代理），还是在公司（用公司的代理），都会有。
好奇怪，这个问题困扰了好几年了......  尤其是在家访问小姐姐视频网站的时候，大片大片的图片或者视频刷新不出来，刷新几次都一样。
好郁闷 :-(

**Comment by AnyWAT** [comment]
未加载资源——提示的那几个网站（比如：*.reddit.com, *.gstatic.com），手动再次添加到直连或代理，哪怕已有此切换规则。。。

**Comment by alexya** [comment]
虽然不能完全解决，但还是谢谢。
