### ISSUE TITLE
添加 http://www.orgloft.com/

### ISSUE THREAD

**Issue by kouhe3** [MatcherAny/whitelist.pac#22]
http://www.orgloft.com/

**Comment by MatcherAny** [comment]
类似这种个人博客我没有怎么添加, 主要原因有两个
1. 博客本身几乎没有大量视频之类消耗vpn流量的资源
2. 大部分这种博客的主机还是在大陆以外的, orgloft.com 就是放在香港, 用vpn访问可能速度更快
