### ISSUE TITLE
建议增加ClashR的默认端口

### ISSUE THREAD

**Issue by dugulingping** [MatcherAny/whitelist.pac#25]
如题，最近抛弃了使用很久的ssr，转到了ClashR这个代理软件。端口是7891
我fork了此项目的我自己已经增加了，但是我希望我的fork源也能写进去，最近用ClashR的人还是蛮多的~

**Comment by dugulingping** [comment]
ClashR是无法改变端口为1080或者10800的，所以我希望你们能新增~

**Comment by xgdgsc** [comment]
是，默认7890的clash for windows也有

**Comment by xgdgsc** [comment]
改用 https://github.com/ifyour/ipac 了

**Comment by MatcherAny** [comment]
添加了
