### ISSUE TITLE
feedly推文内置的国内域名的图片无法正常预览，内详。

### ISSUE THREAD

**Issue by Fezreal** [MatcherAny/whitelist.pac#6]
我相信图片内给出的信息足以让你解决问题。

图片一：
![1](https://user-images.githubusercontent.com/6703674/45725530-daf60680-bbed-11e8-8c4f-174c9d24cac3.jpg)

---------
图片二：
![2](https://user-images.githubusercontent.com/6703674/45725533-dc273380-bbed-11e8-928f-9198d0405dde.jpg)

**Comment by Fezreal** [comment]
@MatcherAny

**Comment by MatcherAny** [comment]
@Fezreal  看起来是这个国内CDN没有添加
