### ISSUE TITLE
使用ip段的方式白名单国内网站

### ISSUE THREAD

**Issue by Fezreal** [MatcherAny/whitelist.pac#7]
https://github.com/LisonFan/china_ip_list/blob/master/SSR/chn_ip.txt

目前你这样一个一个域名手动白名单，不太好吧。

**Comment by MatcherAny** [comment]
真正经常访问的国内网站不会很多，再把主流CDN域名添加进去，一个文件可以用很久的。
最主要原因是ip变化太大，现在没时间搞ip库 :smile:
