### ISSUE TITLE
批改网 | FiF | 快手 | 卡饭论坛 | 抖音 | 千千音乐 | 饿了么 | 乐视 | 博客园分站 | 码云 | 爱范儿 | 九秀直播

### ISSUE THREAD

**Issue by dou4cc** [MatcherAny/whitelist.pac#8]
fifedu.com
pigai.org

**Comment by AnyWAT** [comment]
https://github.com/MatcherAny/whitelist.pac/issues/5#issuecomment-436128466 在大佬未添加前手动走“直接连接”😂

**Comment by dou4cc** [comment]
9xiu.com
ad-survey.com
aicdn.com
aqfen.com
cn.bing.com
bjcathay.com
cnitblog.com
cppblog.com
douyin.com
elemecdn.com
freehao123.com
gifshow.com
ifanr.com
ikafan.com
kuaishou.com
letvcloud.com
oneapm.com
snssdk.com
taihe.com
webtrends.com
xnpic.com
xtgreat.com
yunaq.com
yximgs.com
ele.me
blogjava.net
coding.net
upcdn.net
xiami.ne
szfg.org

**Comment by MatcherAny** [comment]
@dou4cc 大部分已经添加了，少部分网站失效

**Comment by RevenXXX-a** [comment]
> @dou4cc 大部分已经添加了，少部分网站失效

i.mi.com
